### ISSUE TITLE
Feature Request: Add Config File

### ISSUE THREAD

**Issue by RotokEralil** [realguyman/steel#10]
Amazing mod! I am loving it so far, but was wondering if you could add a config file (would love to tweak the values on the pieces slightly).

**Comment by realguyman** [comment]
Thank you, I'm glad you're enjoying it. What sort of configuration are you looking for? Armor rating values? Durability?

**Comment by RotokEralil** [comment]
A good chunk of them lol.
I think the current attributes are knockback resistance, durability, armor defense points, armor toughness (maybe +1 default, since diamond is +2 and netherite is +3), enchantability, repair items (repair with other like items or a steel ingot), For the tools/weapons, Attack damage, speed, harvest level (I think Iron is lvl 2 and diamond is level 3).

So I guess the big ones would be enchantability, armor rating, durability, attack speed, attack damage, maybe knockback resist (since I imagine steel would take a hit better then iron?).
Thanks for hearing me out :D

**Comment by realguyman** [comment]
Diamond armor doesn't have knockback resistance so I didn't apply it for steel.

I've been meaning to extend the wiki to include information about durability, mining speed, and other factors. But anyway, I'll look into methods for developing a configuration system.

**Comment by RotokEralil** [comment]
Ah, apologies (evil out of date wiki I was reading lol). Then dont worry about that one!
And I appreciate you getting back to me!
If you only have time to update the wiki, I think there are a few mods who have excel like charts they have to show the difference for the values for the items (like Gobber or More Gems EDIT: I see now they are made by same team, so they would keep it consistant lol).

**Comment by realguyman** [comment]
@RotokEralil I've implemented a basic configuration file. I can have `v1.2.0` out for 1.18 today. Does this look good? Take a look at the pull request I linked to this issue.

**Comment by RotokEralil** [comment]
@realguyman This looks great! Will only the sword's damage be editable? (I know some prefer using an ax).

**Comment by realguyman** [comment]
I can add axe damage as well.

**Comment by RotokEralil** [comment]
You are awesome!
